CREATE TABLE acteur(id_acteur INT PRIMARY KEY NOT NULL, nom VARCHAR(30));
CREATE TABLE utilisateur(id INT PRIMARY KEY NOT NULL, nom VARCHAR(20));
CREATE TABLE film(id_film INT PRIMARY KEY NOT NULL, titre VARCHAR(30));